// Generated by gencpp from file spencer_detected_person_association/LookupTrackIdsResponse.msg
// DO NOT EDIT!


#ifndef SPENCER_DETECTED_PERSON_ASSOCIATION_MESSAGE_LOOKUPTRACKIDSRESPONSE_H
#define SPENCER_DETECTED_PERSON_ASSOCIATION_MESSAGE_LOOKUPTRACKIDSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spencer_detected_person_association
{
template <class ContainerAllocator>
struct LookupTrackIdsResponse_
{
  typedef LookupTrackIdsResponse_<ContainerAllocator> Type;

  LookupTrackIdsResponse_()
    : was_found()
    , track_ids()  {
    }
  LookupTrackIdsResponse_(const ContainerAllocator& _alloc)
    : was_found(_alloc)
    , track_ids(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _was_found_type;
  _was_found_type was_found;

   typedef std::vector<uint64_t, typename ContainerAllocator::template rebind<uint64_t>::other >  _track_ids_type;
  _track_ids_type track_ids;





  typedef boost::shared_ptr< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LookupTrackIdsResponse_

typedef ::spencer_detected_person_association::LookupTrackIdsResponse_<std::allocator<void> > LookupTrackIdsResponse;

typedef boost::shared_ptr< ::spencer_detected_person_association::LookupTrackIdsResponse > LookupTrackIdsResponsePtr;
typedef boost::shared_ptr< ::spencer_detected_person_association::LookupTrackIdsResponse const> LookupTrackIdsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator1> & lhs, const ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.was_found == rhs.was_found &&
    lhs.track_ids == rhs.track_ids;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator1> & lhs, const ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spencer_detected_person_association

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f75a3066dabe6cedc87592cb01e78f64";
  }

  static const char* value(const ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf75a3066dabe6cedULL;
  static const uint64_t static_value2 = 0xc87592cb01e78f64ULL;
};

template<class ContainerAllocator>
struct DataType< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spencer_detected_person_association/LookupTrackIdsResponse";
  }

  static const char* value(const ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[]        was_found           # False if no associated track could be found (e.g. because the detection was false alarm). Has same length as detection_ids.\n"
"uint64[]      track_ids           # ID of the associated tracks. Undefined if 'was_found' is false. Has same length as detection_ids.\n"
;
  }

  static const char* value(const ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.was_found);
      stream.next(m.track_ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LookupTrackIdsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spencer_detected_person_association::LookupTrackIdsResponse_<ContainerAllocator>& v)
  {
    s << indent << "was_found[]" << std::endl;
    for (size_t i = 0; i < v.was_found.size(); ++i)
    {
      s << indent << "  was_found[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.was_found[i]);
    }
    s << indent << "track_ids[]" << std::endl;
    for (size_t i = 0; i < v.track_ids.size(); ++i)
    {
      s << indent << "  track_ids[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.track_ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPENCER_DETECTED_PERSON_ASSOCIATION_MESSAGE_LOOKUPTRACKIDSRESPONSE_H
