// Generated by gencpp from file roboteq_diff_msgs/Pose.msg
// DO NOT EDIT!


#ifndef ROBOTEQ_DIFF_MSGS_MESSAGE_POSE_H
#define ROBOTEQ_DIFF_MSGS_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roboteq_diff_msgs/Point.h>
#include <roboteq_diff_msgs/Quaternion.h>

namespace roboteq_diff_msgs
{
template <class ContainerAllocator>
struct Pose_
{
  typedef Pose_<ContainerAllocator> Type;

  Pose_()
    : position()
    , orientation()  {
    }
  Pose_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , orientation(_alloc)  {
  (void)_alloc;
    }



   typedef  ::roboteq_diff_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::roboteq_diff_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::roboteq_diff_msgs::Pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboteq_diff_msgs::Pose_<ContainerAllocator> const> ConstPtr;

}; // struct Pose_

typedef ::roboteq_diff_msgs::Pose_<std::allocator<void> > Pose;

typedef boost::shared_ptr< ::roboteq_diff_msgs::Pose > PosePtr;
typedef boost::shared_ptr< ::roboteq_diff_msgs::Pose const> PoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboteq_diff_msgs::Pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboteq_diff_msgs::Pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboteq_diff_msgs::Pose_<ContainerAllocator1> & lhs, const ::roboteq_diff_msgs::Pose_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.orientation == rhs.orientation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboteq_diff_msgs::Pose_<ContainerAllocator1> & lhs, const ::roboteq_diff_msgs::Pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboteq_diff_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roboteq_diff_msgs::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_diff_msgs::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_diff_msgs::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_diff_msgs::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_diff_msgs::Pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_diff_msgs::Pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboteq_diff_msgs::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ec5a94781ee76f5aa190025baf9a1a4";
  }

  static const char* value(const ::roboteq_diff_msgs::Pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ec5a94781ee76f5ULL;
  static const uint64_t static_value2 = 0xaa190025baf9a1a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboteq_diff_msgs::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboteq_diff_msgs/Pose";
  }

  static const char* value(const ::roboteq_diff_msgs::Pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboteq_diff_msgs::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: roboteq_diff_msgs/Point\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"\n"
"================================================================================\n"
"MSG: roboteq_diff_msgs/Quaternion\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 w\n"
;
  }

  static const char* value(const ::roboteq_diff_msgs::Pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboteq_diff_msgs::Pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboteq_diff_msgs::Pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboteq_diff_msgs::Pose_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::roboteq_diff_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::roboteq_diff_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTEQ_DIFF_MSGS_MESSAGE_POSE_H
