// Generated by gencpp from file roboteq_diff_msgs/RequestOdometryCovariances.msg
// DO NOT EDIT!


#ifndef ROBOTEQ_DIFF_MSGS_MESSAGE_REQUESTODOMETRYCOVARIANCES_H
#define ROBOTEQ_DIFF_MSGS_MESSAGE_REQUESTODOMETRYCOVARIANCES_H

#include <ros/service_traits.h>


#include <roboteq_diff_msgs/RequestOdometryCovariancesRequest.h>
#include <roboteq_diff_msgs/RequestOdometryCovariancesResponse.h>


namespace roboteq_diff_msgs
{

struct RequestOdometryCovariances
{

typedef RequestOdometryCovariancesRequest Request;
typedef RequestOdometryCovariancesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestOdometryCovariances
} // namespace roboteq_diff_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboteq_diff_msgs::RequestOdometryCovariances > {
  static const char* value()
  {
    return "be649028e78f3c3af92cf2be027c065f";
  }

  static const char* value(const ::roboteq_diff_msgs::RequestOdometryCovariances&) { return value(); }
};

template<>
struct DataType< ::roboteq_diff_msgs::RequestOdometryCovariances > {
  static const char* value()
  {
    return "roboteq_diff_msgs/RequestOdometryCovariances";
  }

  static const char* value(const ::roboteq_diff_msgs::RequestOdometryCovariances&) { return value(); }
};


// service_traits::MD5Sum< ::roboteq_diff_msgs::RequestOdometryCovariancesRequest> should match
// service_traits::MD5Sum< ::roboteq_diff_msgs::RequestOdometryCovariances >
template<>
struct MD5Sum< ::roboteq_diff_msgs::RequestOdometryCovariancesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboteq_diff_msgs::RequestOdometryCovariances >::value();
  }
  static const char* value(const ::roboteq_diff_msgs::RequestOdometryCovariancesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboteq_diff_msgs::RequestOdometryCovariancesRequest> should match
// service_traits::DataType< ::roboteq_diff_msgs::RequestOdometryCovariances >
template<>
struct DataType< ::roboteq_diff_msgs::RequestOdometryCovariancesRequest>
{
  static const char* value()
  {
    return DataType< ::roboteq_diff_msgs::RequestOdometryCovariances >::value();
  }
  static const char* value(const ::roboteq_diff_msgs::RequestOdometryCovariancesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboteq_diff_msgs::RequestOdometryCovariancesResponse> should match
// service_traits::MD5Sum< ::roboteq_diff_msgs::RequestOdometryCovariances >
template<>
struct MD5Sum< ::roboteq_diff_msgs::RequestOdometryCovariancesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboteq_diff_msgs::RequestOdometryCovariances >::value();
  }
  static const char* value(const ::roboteq_diff_msgs::RequestOdometryCovariancesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboteq_diff_msgs::RequestOdometryCovariancesResponse> should match
// service_traits::DataType< ::roboteq_diff_msgs::RequestOdometryCovariances >
template<>
struct DataType< ::roboteq_diff_msgs::RequestOdometryCovariancesResponse>
{
  static const char* value()
  {
    return DataType< ::roboteq_diff_msgs::RequestOdometryCovariances >::value();
  }
  static const char* value(const ::roboteq_diff_msgs::RequestOdometryCovariancesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTEQ_DIFF_MSGS_MESSAGE_REQUESTODOMETRYCOVARIANCES_H
