// Generated by gencpp from file wheelchair_navigation/ModeChangeResponse.msg
// DO NOT EDIT!


#ifndef WHEELCHAIR_NAVIGATION_MESSAGE_MODECHANGERESPONSE_H
#define WHEELCHAIR_NAVIGATION_MESSAGE_MODECHANGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheelchair_navigation
{
template <class ContainerAllocator>
struct ModeChangeResponse_
{
  typedef ModeChangeResponse_<ContainerAllocator> Type;

  ModeChangeResponse_()
    {
    }
  ModeChangeResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ModeChangeResponse_

typedef ::wheelchair_navigation::ModeChangeResponse_<std::allocator<void> > ModeChangeResponse;

typedef boost::shared_ptr< ::wheelchair_navigation::ModeChangeResponse > ModeChangeResponsePtr;
typedef boost::shared_ptr< ::wheelchair_navigation::ModeChangeResponse const> ModeChangeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace wheelchair_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheelchair_navigation/ModeChangeResponse";
  }

  static const char* value(const ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeChangeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::wheelchair_navigation::ModeChangeResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // WHEELCHAIR_NAVIGATION_MESSAGE_MODECHANGERESPONSE_H
