// Generated by gencpp from file wheelchair_navigation/MotorReference.msg
// DO NOT EDIT!


#ifndef WHEELCHAIR_NAVIGATION_MESSAGE_MOTORREFERENCE_H
#define WHEELCHAIR_NAVIGATION_MESSAGE_MOTORREFERENCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheelchair_navigation
{
template <class ContainerAllocator>
struct MotorReference_
{
  typedef MotorReference_<ContainerAllocator> Type;

  MotorReference_()
    : ref1(0)
    , ref2(0)  {
    }
  MotorReference_(const ContainerAllocator& _alloc)
    : ref1(0)
    , ref2(0)  {
  (void)_alloc;
    }



   typedef int32_t _ref1_type;
  _ref1_type ref1;

   typedef int32_t _ref2_type;
  _ref2_type ref2;





  typedef boost::shared_ptr< ::wheelchair_navigation::MotorReference_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheelchair_navigation::MotorReference_<ContainerAllocator> const> ConstPtr;

}; // struct MotorReference_

typedef ::wheelchair_navigation::MotorReference_<std::allocator<void> > MotorReference;

typedef boost::shared_ptr< ::wheelchair_navigation::MotorReference > MotorReferencePtr;
typedef boost::shared_ptr< ::wheelchair_navigation::MotorReference const> MotorReferenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheelchair_navigation::MotorReference_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheelchair_navigation::MotorReference_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wheelchair_navigation::MotorReference_<ContainerAllocator1> & lhs, const ::wheelchair_navigation::MotorReference_<ContainerAllocator2> & rhs)
{
  return lhs.ref1 == rhs.ref1 &&
    lhs.ref2 == rhs.ref2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wheelchair_navigation::MotorReference_<ContainerAllocator1> & lhs, const ::wheelchair_navigation::MotorReference_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wheelchair_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wheelchair_navigation::MotorReference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheelchair_navigation::MotorReference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheelchair_navigation::MotorReference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheelchair_navigation::MotorReference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheelchair_navigation::MotorReference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheelchair_navigation::MotorReference_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheelchair_navigation::MotorReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c572d6e3cd025887d29d3e38d6d8c7f5";
  }

  static const char* value(const ::wheelchair_navigation::MotorReference_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc572d6e3cd025887ULL;
  static const uint64_t static_value2 = 0xd29d3e38d6d8c7f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::wheelchair_navigation::MotorReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheelchair_navigation/MotorReference";
  }

  static const char* value(const ::wheelchair_navigation::MotorReference_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheelchair_navigation::MotorReference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ref1\n"
"int32 ref2\n"
;
  }

  static const char* value(const ::wheelchair_navigation::MotorReference_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheelchair_navigation::MotorReference_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ref1);
      stream.next(m.ref2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorReference_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheelchair_navigation::MotorReference_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheelchair_navigation::MotorReference_<ContainerAllocator>& v)
  {
    s << indent << "ref1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ref1);
    s << indent << "ref2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ref2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELCHAIR_NAVIGATION_MESSAGE_MOTORREFERENCE_H
