(cl:defpackage roboteq_diff_msgs-srv
  (:use )
  (:export
   "REQUESTODOMETRYCOVARIANCES"
   "<REQUESTODOMETRYCOVARIANCES-REQUEST>"
   "REQUESTODOMETRYCOVARIANCES-REQUEST"
   "<REQUESTODOMETRYCOVARIANCES-RESPONSE>"
   "REQUESTODOMETRYCOVARIANCES-RESPONSE"
   "REQUESTPARAM"
   "<REQUESTPARAM-REQUEST>"
   "REQUESTPARAM-REQUEST"
   "<REQUESTPARAM-RESPONSE>"
   "REQUESTPARAM-RESPONSE"
  ))

