(cl:in-package wheelchair_navigation-msg)
(cl:export '(AMPS1-VAL
          AMPS1
          AMPS2-VAL
          AMPS2
          V_INT-VAL
          V_INT
          V_BATT-VAL
          V_BATT
          RPM1-VAL
          RPM1
          RPM2-VAL
          RPM2
          ENCODER1-VAL
          ENCODER1
          ENCODER2-VAL
          ENCODER2
          CMD1-VAL
          CMD1
          CMD2-VAL
          CMD2
          TEMP1-VAL
          TEMP1
          TEMP2-VAL
          TEMP2
          FAULTFLAGS-VAL
          FAULTFLAGS
          MODE-VAL
          MODE
))