// Generated by gencpp from file srl_laser_segmentation/BoolStamped.msg
// DO NOT EDIT!


#ifndef SRL_LASER_SEGMENTATION_MESSAGE_BOOLSTAMPED_H
#define SRL_LASER_SEGMENTATION_MESSAGE_BOOLSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace srl_laser_segmentation
{
template <class ContainerAllocator>
struct BoolStamped_
{
  typedef BoolStamped_<ContainerAllocator> Type;

  BoolStamped_()
    : header()
    , data(false)  {
    }
  BoolStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> const> ConstPtr;

}; // struct BoolStamped_

typedef ::srl_laser_segmentation::BoolStamped_<std::allocator<void> > BoolStamped;

typedef boost::shared_ptr< ::srl_laser_segmentation::BoolStamped > BoolStampedPtr;
typedef boost::shared_ptr< ::srl_laser_segmentation::BoolStamped const> BoolStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srl_laser_segmentation::BoolStamped_<ContainerAllocator1> & lhs, const ::srl_laser_segmentation::BoolStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srl_laser_segmentation::BoolStamped_<ContainerAllocator1> & lhs, const ::srl_laser_segmentation::BoolStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srl_laser_segmentation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "542e22b190dc8e6eb476d50dda88feb7";
  }

  static const char* value(const ::srl_laser_segmentation::BoolStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x542e22b190dc8e6eULL;
  static const uint64_t static_value2 = 0xb476d50dda88feb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srl_laser_segmentation/BoolStamped";
  }

  static const char* value(const ::srl_laser_segmentation::BoolStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::srl_laser_segmentation::BoolStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoolStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srl_laser_segmentation::BoolStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srl_laser_segmentation::BoolStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRL_LASER_SEGMENTATION_MESSAGE_BOOLSTAMPED_H
