# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roboteq_diff_msgs/RequestOdometryCovariancesRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class RequestOdometryCovariancesRequest(genpy.Message):
  _md5sum = "6aac6c697d5414bc0fcede8c33981d0e"
  _type = "roboteq_diff_msgs/RequestOdometryCovariancesRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Empty empty

================================================================================
MSG: std_msgs/Empty
"""
  __slots__ = ['empty']
  _slot_types = ['std_msgs/Empty']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       empty

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RequestOdometryCovariancesRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.empty is None:
        self.empty = std_msgs.msg.Empty()
    else:
      self.empty = std_msgs.msg.Empty()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.empty is None:
        self.empty = std_msgs.msg.Empty()
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.empty is None:
        self.empty = std_msgs.msg.Empty()
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roboteq_diff_msgs/RequestOdometryCovariancesResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import roboteq_diff_msgs.msg

class RequestOdometryCovariancesResponse(genpy.Message):
  _md5sum = "0ca4cf3225406c524934bf7fd2c86a11"
  _type = "roboteq_diff_msgs/RequestOdometryCovariancesResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """OdometryCovariances odometry_covariances


================================================================================
MSG: roboteq_diff_msgs/OdometryCovariances
float64[36] pose_covariance
float64[36] twist_covariance
"""
  __slots__ = ['odometry_covariances']
  _slot_types = ['roboteq_diff_msgs/OdometryCovariances']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       odometry_covariances

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RequestOdometryCovariancesResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.odometry_covariances is None:
        self.odometry_covariances = roboteq_diff_msgs.msg.OdometryCovariances()
    else:
      self.odometry_covariances = roboteq_diff_msgs.msg.OdometryCovariances()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_36d().pack(*self.odometry_covariances.pose_covariance))
      buff.write(_get_struct_36d().pack(*self.odometry_covariances.twist_covariance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.odometry_covariances is None:
        self.odometry_covariances = roboteq_diff_msgs.msg.OdometryCovariances()
      end = 0
      start = end
      end += 288
      self.odometry_covariances.pose_covariance = _get_struct_36d().unpack(str[start:end])
      start = end
      end += 288
      self.odometry_covariances.twist_covariance = _get_struct_36d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.odometry_covariances.pose_covariance.tostring())
      buff.write(self.odometry_covariances.twist_covariance.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.odometry_covariances is None:
        self.odometry_covariances = roboteq_diff_msgs.msg.OdometryCovariances()
      end = 0
      start = end
      end += 288
      self.odometry_covariances.pose_covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      start = end
      end += 288
      self.odometry_covariances.twist_covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_36d = None
def _get_struct_36d():
    global _struct_36d
    if _struct_36d is None:
        _struct_36d = struct.Struct("<36d")
    return _struct_36d
class RequestOdometryCovariances(object):
  _type          = 'roboteq_diff_msgs/RequestOdometryCovariances'
  _md5sum = 'be649028e78f3c3af92cf2be027c065f'
  _request_class  = RequestOdometryCovariancesRequest
  _response_class = RequestOdometryCovariancesResponse
